spring:
  application:
    name: microservice-gateway-zuul-filter

server:
  port: 8091

eureka:
  client:
   service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
