server:
  port: 8084
spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
