server:
  port: 8100

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaotao0110/profile
          search-paths: /
          username: xiaotao0110
          password: 19970110xt
          default-label: master

