server:
  port: 8085
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


