server:
  port: 8089
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig:movie-ribbon-hystrix
  appConfig:movie-ribbon-hystrix